interface Validator{
    isValid(value: string | number);
}

interface ValidatorMessage{
    setMessage(message: string);
}

class EmailValidator implements Validator, ValidatorMessage{
    isValid(value: string | number) {
        console.log("some validator logic");
    }

    setMessage(message: string) {
        console.log("another interface implementation")
    }
}


// Generated by https://quicktype.io

export interface Demo {
    _id:           string;
    index:         number;
    guid:          string;
    isActive:      boolean;
    balance:       string;
    picture:       string;
    age:           number;
    eyeColor:      string;
    name:          string;
    gender:        string;
    company:       string;
    email:         string;
    phone:         string;
    address:       string;
    about:         string;
    registered:    string;
    latitude:      number;
    longitude:     number;
    tags:          string[];
    friends:       Friend[];
    greeting:      string;
    favoriteFruit: string;
}

export interface Friend {
    id:   number;
    name: string;
}
