export type ProductType = {
  productId: number;
  productName: string;
  productImage: string;
  productPrice: number;
  productSalePrice: number;
  productStock: number;
};
// Generated by https://quicktype.io

export type UserType = {
  localId: string;
  email: string;
  displayName: string;
  idToken: string;
  registered: boolean;
  refreshToken: string;
  expiresIn: string;
};
